name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install
      - run: |
          yarn run all
  test:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      # - uses: actions/checkout@v3
      # # Works with only one json file:
      # - uses: ./
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     current_json: "./test_data/current.json"
      # Works in diff mode with 2 json files:
      - uses: ./
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          current_json: "./test_data/current.json"
          old_json: "./test_data/old.json"